// Static styles — extracted from Analyzer_Demo.js for readability.
// Pure function: takes theme params, returns styles object.

export function buildStaticStyles(theme, isDarkMode, showDataSummary) {
  return {
      base: {
        button: {
          padding: "6px 12px",
          border: "none",
          borderRadius: "6px",
          fontSize: "12px",
          fontWeight: "500",
          cursor: "pointer",
          transition: "all 0.15s ease",
        },
        input: {
          padding: "6px 10px",
          border: `1px solid ${theme.borderSecondary}`,
          borderRadius: "6px",
          fontSize: "12px",
          color: theme.textSecondary,
          backgroundColor: theme.bgPrimary,
          transition: "all 0.15s ease",
        },
        flexRow: { display: "flex", alignItems: "center", gap: "8px" },
        flexCol: { display: "flex", flexDirection: "column" },
        card: {
          backgroundColor: theme.bgPrimary,
          borderRadius: "8px",
          border: "none",
          boxShadow: isDarkMode
            ? "0 1px 3px rgba(0, 0, 0, 0.3)"
            : "0 1px 2px rgba(0, 0, 0, 0.05)",
        },
      },
      buttonGroup: {
        display: "flex",
        gap: "4px",
        backgroundColor: theme.bgQuaternary,
        padding: "4px",
        borderRadius: "8px",
        border: `1px solid ${theme.borderSecondary}`,
      },
      buttonGroupBtn: {
        padding: "4px 10px",
        borderRadius: "4px",
        backgroundColor: "transparent",
        color: theme.textTertiary,
        border: "none",
        fontSize: "12px",
        fontWeight: "500",
        cursor: "pointer",
        transition: "all 0.15s ease",
      },
      buttonGroupBtnActive: {
        backgroundColor: theme.accentPrimary,
        color: "white",
      },
      topSection: {
        display: "flex",
        flexDirection: "column",
        gap: "12px",
        marginBottom: "12px",
      },
      statBoxContainer: {
        display: "flex",
        gap: "12px",
        flexWrap: "nowrap",
        width: "100%",
      },
      controlsHeader: {
        display: "flex",
        alignItems: "center",
        padding: "14px 18px",
        backgroundColor: "transparent",
        borderBottom: `1px solid ${
          isDarkMode ? "rgba(148, 163, 184, 0.1)" : "rgba(229, 231, 235, 0.5)"
        }`,
        gap: "16px",
        flexWrap: "wrap",
      },
      controlsHeaderTitle: {
        fontSize: "14px",
        fontWeight: "700",
        color: theme.textPrimary,
        display: "flex",
        alignItems: "center",
        gap: "8px",
      },
      controlsHeaderChevron: { fontSize: "12px", color: theme.textTertiary },
      controlsContent: { padding: "18px", overflowY: "visible" },
      controlsRow: {
        display: "flex",
        flexWrap: "wrap",
        gap: "20px",
        alignItems: "end",
      },
      controlGroup: {
        display: "flex",
        flexDirection: "column",
        minWidth: "140px",
        flex: "1 1 auto",
      },
      controlGroupCompact: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        gap: "8px",
        flex: "1 1 auto",
      },
      label: {
        fontSize: "13px",
        fontWeight: "normal",
        color: theme.textPrimary,
        marginBottom: "6px",
      },
      labelCompact: {
        fontSize: "12px",
        fontWeight: "500",
        color: theme.textSecondary,
        marginBottom: "0",
        marginRight: "4px",
        whiteSpace: "nowrap",
      },
      resetButton: {
        backgroundColor: "#ef4444",
        color: "white",
        whiteSpace: "nowrap",
        padding: "6px 12px",
        border: "none",
        borderRadius: "6px",
        fontSize: "12px",
        fontWeight: "500",
        cursor: "pointer",
      },
      filterSearchContainer: { position: "relative", minWidth: "200px" },
      filterSearchInput: {
        width: "100%",
        outline: "none",
        padding: "6px 10px",
        border: `1px solid ${theme.borderSecondary}`,
        borderRadius: "6px",
        fontSize: "12px",
        color: theme.textSecondary,
        backgroundColor: theme.bgPrimary,
        transition: "all 0.15s ease",
      },
      filterSuggestionItem: {
        display: "flex",
        alignItems: "center",
        padding: "8px 12px",
        cursor: "pointer",
        borderBottom: `1px solid ${theme.bgQuaternary}`,
      },
      filterSuggestionName: {
        fontSize: "13px",
        color: theme.textPrimary,
        fontWeight: "500",
        cursor: "pointer",
        userSelect: "none",
      },
      filterGroupHeader: {
        padding: "8px 12px",
        backgroundColor: theme.bgTertiary,
        fontSize: "11px",
        color: theme.textTertiary,
        fontWeight: "600",
        textTransform: "uppercase",
        letterSpacing: "0.05em",
        borderBottom: `1px solid ${theme.borderPrimary}`,
      },
      mainContent: {
        display: "flex",
        gap: "12px",
        alignItems: "flex-start",
        position: "relative",
      },
      leftPanel: {
        display: "flex",
        flexDirection: "column",
        minWidth: "300px",
        maxWidth: "350px",
      },
      statBoxLeft: {
        display: "flex",
        flexDirection: "column",
        flex: "1 1 0",
        position: "relative",
        zIndex: 1,
      },
      statBoxRight: {
        display: "flex",
        flexDirection: "column",
        alignItems: "flex-end",
        justifyContent: "flex-start",
        gap: "12px",
        minWidth: "130px",
        position: "relative",
        zIndex: 1,
      },
      statBoxActive: {
        border: "none",
        backgroundColor: isDarkMode
          ? "rgba(129, 140, 248, 0.15)"
          : theme.statBoxActiveBg,
        transform: "translateY(-2px)",
        boxShadow: isDarkMode
          ? `0 4px 16px rgba(129, 140, 248, 0.4), 0 0 0 1px rgba(129, 140, 248, 0.5)`
          : `0 4px 12px rgba(99, 102, 241, 0.2), 0 0 0 1px ${theme.accentPrimary}`,
      },
      statBoxInactive: { opacity: 0.9 },
      statTitle: {
        fontSize: "12px",
        fontWeight: "600",
        color: theme.textTertiary,
        marginBottom: "8px",
        textTransform: "uppercase",
        letterSpacing: "0.08em",
        display: "flex",
        alignItems: "center",
        gap: "6px",
      },
      statValue: {
        fontSize: "28px",
        fontWeight: "800",
        color: theme.textPrimary,
        lineHeight: "1.1",
        marginBottom: "10px",
        letterSpacing: "-0.02em",
      },
      statPeriod: {
        fontSize: "11px",
        color: theme.textQuaternary,
        marginBottom: "0",
        fontWeight: "500",
        display: "flex",
        alignItems: "center",
        gap: "4px",
      },
      changeContainer: {
        display: "flex",
        flexDirection: "column",
        alignItems: "flex-end",
        gap: "6px",
        marginBottom: "0",
        paddingLeft: "12px",
        borderLeft: `2px solid ${theme.bgQuaternary}`,
      },
      changeValue: {
        fontSize: "15px",
        fontWeight: "700",
        display: "flex",
        alignItems: "center",
        gap: "4px",
      },
      changePercent: {
        fontSize: "11px",
        fontWeight: "600",
        padding: "4px 10px",
        borderRadius: "16px",
        display: "inline-block",
      },
      undoButton: {
        position: "absolute",
        top: "12px",
        left: "12px",
        backgroundColor: theme.bgPrimary,
        border: `1px solid ${theme.borderSecondary}`,
        borderRadius: "6px",
        padding: "4px 6px",
        fontSize: "16px",
        cursor: "pointer",
        zIndex: 10,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        minWidth: "28px",
        minHeight: "28px",
        opacity: 1,
        color: theme.textSecondary,
      },
      undoButtonDisabled: { opacity: 0.4, cursor: "not-allowed" },
      shareModal: {
        position: "fixed",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: theme.overlayBg,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 10000,
      },
      shareModalContent: {
        backgroundColor: theme.bgPrimary,
        borderRadius: "8px",
        padding: "24px",
        maxWidth: "500px",
        width: "90%",
        boxShadow:
          "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
      },
      shareModalHeader: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: "20px",
      },
      shareModalTitle: {
        fontSize: "20px",
        fontWeight: "600",
        color: theme.textPrimary,
      },
      shareModalClose: {
        background: "none",
        border: "none",
        fontSize: "24px",
        color: theme.textTertiary,
        cursor: "pointer",
        padding: "0",
        width: "32px",
        height: "32px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: "4px",
      },
      shareLinkContainer: { display: "flex", gap: "8px", marginBottom: "16px" },
      shareLinkInput: {
        flex: 1,
        padding: "10px 12px",
        border: `1px solid ${theme.borderSecondary}`,
        borderRadius: "6px",
        fontSize: "14px",
        fontFamily: "monospace",
        backgroundColor: theme.bgTertiary,
        color: theme.textSecondary,
      },
      shareCopyButton: {
        padding: "10px 20px",
        backgroundColor: theme.accentPrimary,
        color: "white",
        fontSize: "14px",
        border: "none",
        borderRadius: "6px",
        fontWeight: "500",
        cursor: "pointer",
      },
      shareInstructions: {
        fontSize: "14px",
        color: theme.textTertiary,
        lineHeight: "1.5",
      },
      shareCodeSection: { marginBottom: "24px" },
      shareCodeLabel: {
        fontSize: "12px",
        fontWeight: "500",
        color: theme.textTertiary,
        marginBottom: "8px",
        display: "block",
      },
      pasteCodeSection: {
        marginTop: "24px",
        paddingTop: "24px",
        borderTop: `1px solid ${theme.borderPrimary}`,
      },
      pasteCodeInput: {
        width: "100%",
        padding: "10px 12px",
        border: `1px solid ${theme.borderSecondary}`,
        borderRadius: "6px",
        fontSize: "14px",
        fontFamily: "monospace",
        backgroundColor: theme.bgTertiary,
        color: theme.textSecondary,
        marginBottom: "8px",
      },
      pasteCodeError: {
        fontSize: "12px",
        color: theme.dangerText,
        marginBottom: "8px",
      },
      shareLoadButton: {
        padding: "10px 20px",
        backgroundColor: theme.success,
        color: "white",
        fontSize: "14px",
        width: "100%",
        border: "none",
        borderRadius: "6px",
        fontWeight: "500",
        cursor: "pointer",
      },
      topXControl: {
        position: "absolute",
        top: "12px",
        right: "12px",
        backgroundColor: theme.bgPrimary,
        border: `1px solid ${theme.borderSecondary}`,
        borderRadius: "8px",
        padding: "8px 12px",
        fontSize: "13px",
        cursor: "pointer",
        zIndex: 10,
        display: "flex",
        alignItems: "center",
        gap: "8px",
        minHeight: "40px",
        color: theme.textSecondary,
      },
      topXControlDropdown: {
        position: "absolute",
        top: "100%",
        right: "0",
        marginTop: "8px",
        backgroundColor: theme.bgPrimary,
        border: `1px solid ${theme.borderSecondary}`,
        borderRadius: "8px",
        minWidth: "280px",
        maxWidth: "400px",
        maxHeight: "500px",
        overflowY: "auto",
        zIndex: 1000,
        padding: "12px",
      },
      topXControlHeader: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: "12px",
        paddingBottom: "8px",
        borderBottom: `1px solid ${theme.borderPrimary}`,
      },
      topXControlTitle: {
        fontSize: "14px",
        fontWeight: "600",
        color: theme.textSecondary,
      },
      topXModeToggle: {
        display: "flex",
        gap: "4px",
        backgroundColor: theme.bgQuaternary,
        padding: "4px",
        borderRadius: "6px",
        marginBottom: "12px",
      },
      topXInput: {
        width: "100%",
        padding: "6px 8px",
        border: `1px solid ${theme.borderSecondary}`,
        borderRadius: "4px",
        fontSize: "13px",
        marginBottom: "12px",
        backgroundColor: theme.bgPrimary,
        color: theme.textSecondary,
      },
      categorySelectionList: {
        display: "flex",
        flexDirection: "column",
        gap: "4px",
        maxHeight: "300px",
        overflowY: "auto",
      },
      categorySelectionItem: {
        display: "flex",
        alignItems: "center",
        padding: "6px 8px",
        borderRadius: "4px",
        cursor: "pointer",
        color: theme.textSecondary,
      },
      categoryCheckbox: {
        width: "16px",
        height: "16px",
        marginRight: "8px",
        cursor: "pointer",
        accentColor: theme.accentPrimary,
      },
      advancedFiltersHeader: {
        padding: "24px 24px 20px",
        borderBottom: `1px solid ${
          isDarkMode ? "rgba(75, 85, 99, 0.2)" : "rgba(229, 231, 235, 0.5)"
        }`,
        backgroundColor: theme.bgTertiary,
        position: "sticky",
        top: 0,
        zIndex: 10,
      },
      advancedFiltersTitle: {
        fontSize: "18px",
        fontWeight: "600",
        color: theme.textSecondary,
        margin: "0",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
      },
      closeButton: {
        background: "none",
        border: "none",
        fontSize: "24px",
        color: theme.textTertiary,
        cursor: "pointer",
        padding: "0",
        width: "32px",
        height: "32px",
        borderRadius: "6px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
      },
      advancedFiltersContent: { padding: "24px" },
      filterSection: { marginBottom: "24px" },
      sectionTitle: {
        fontSize: "14px",
        fontWeight: "600",
        color: theme.textSecondary,
        marginBottom: "16px",
        textTransform: "uppercase",
        letterSpacing: "0.05em",
        borderBottom: `1px solid ${
          isDarkMode ? "rgba(75, 85, 99, 0.3)" : "rgba(229, 231, 235, 0.6)"
        }`,
        paddingBottom: "8px",
      },
      modernSelect: {
        width: "100%",
        padding: "8px 12px",
        border: `1px solid ${theme.borderSecondary}`,
        borderRadius: "8px",
        fontSize: "14px",
        color: theme.textSecondary,
        backgroundColor: theme.bgPrimary,
        cursor: "pointer",
        appearance: "none",
        backgroundImage:
          "url(\"data:image/svg+xml;charset=UTF-8,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3e%3cpolyline points='6,9 12,15 18,9'%3e%3c/polyline%3e%3c/svg%3e\")",
        backgroundRepeat: "no-repeat",
        backgroundPosition: "right 12px center",
        backgroundSize: "16px",
        paddingRight: "48px",
      },
      modernInput: {
        width: "100%",
        padding: "8px 12px",
        border: `1px solid ${theme.borderSecondary}`,
        borderRadius: "8px",
        fontSize: "14px",
        color: theme.textSecondary,
        backgroundColor: theme.bgPrimary,
        boxSizing: "border-box",
      },
      inputGroup: { display: "flex", flexDirection: "column", gap: "8px" },
      modernLabel: {
        fontSize: "13px",
        fontWeight: "500",
        color: theme.textTertiary,
        marginBottom: "6px",
      },
      checkboxContainer: {
        border: `1px solid ${
          isDarkMode ? "rgba(75, 85, 99, 0.3)" : "rgba(229, 231, 235, 0.6)"
        }`,
        borderRadius: "8px",
        padding: "8px",
        backgroundColor: theme.bgPrimary,
        maxHeight: "200px",
        overflowY: "auto",
      },
      checkboxItem: {
        display: "flex",
        alignItems: "center",
        padding: "6px 8px",
        cursor: "pointer",
        borderRadius: "4px",
      },
      checkboxInput: {
        width: "16px",
        height: "16px",
        marginRight: "8px",
        cursor: "pointer",
        accentColor: theme.accentPrimary,
      },
      checkboxLabel: {
        fontSize: "13px",
        color: theme.textSecondary,
        cursor: "pointer",
        userSelect: "none",
      },
      filterDropdown: {
        border: `1px solid ${
          isDarkMode ? "rgba(75, 85, 99, 0.3)" : "rgba(229, 231, 235, 0.6)"
        }`,
        borderRadius: "8px",
        backgroundColor: theme.bgPrimary,
        marginBottom: "8px",
      },
      filterDropdownHeader: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        padding: "10px 12px",
        cursor: "pointer",
        borderRadius: "6px",
      },
      filterDropdownTitle: {
        fontSize: "14px",
        fontWeight: "500",
        color: theme.textSecondary,
        display: "flex",
        alignItems: "center",
        gap: "8px",
      },
      filterDropdownChevron: {
        fontSize: "12px",
        color: theme.textTertiary,
        transition: "transform 0.18s ease",
      },
      filterDropdownContent: {
        maxHeight: "200px",
        overflowY: "auto",
        padding: "8px",
        borderTop: `1px solid ${theme.borderPrimary}`,
        animation: "dropdownSlideIn 0.18s ease",
      },
      filterSelectedCount: {
        fontSize: "11px",
        color: theme.accentPrimary,
        fontWeight: "600",
        marginLeft: "4px",
      },
      queryInputGroup: {
        display: "flex",
        flexDirection: "column",
        gap: "4px",
        position: "relative",
      },
      queryLabelContainer: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: "10px",
        marginBottom: "4px",
      },
      queryLabel: {
        fontSize: "20px",
        fontWeight: "600",
        textAlign: "center",
        letterSpacing: "-0.02em",
        background:
          "linear-gradient(135deg, #4c51bf 0%, #5b21b6 25%, #a855f7 50%, #2563eb 75%, #0891b2 100%)",
        WebkitBackgroundClip: "text",
        WebkitTextFillColor: "transparent",
        backgroundClip: "text",
        fontFamily:
          "'Inter', 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif",
        position: "relative",
      },
      queryTooltipIcon: {
        position: "relative",
        cursor: "pointer",
        fontSize: "12px",
        color: "#9ca3af",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        width: "16px",
        height: "16px",
      },
      queryTooltip: {
        position: "absolute",
        top: "calc(100% + 8px)",
        left: "50%",
        transform: "translateX(-50%)",
        padding: "10px 14px",
        backgroundColor: theme.bgPrimary,
        color: theme.textSecondary,
        fontSize: "11px",
        borderRadius: "8px",
        zIndex: 1000,
        pointerEvents: "none",
        textAlign: "left",
        lineHeight: "1.5",
        border: `1px solid ${theme.borderPrimary}`,
        fontFamily: "'Inter', 'Segoe UI', sans-serif",
        width: "320px",
        maxWidth: "320px",
        wordWrap: "break-word",
        whiteSpace: "normal",
      },
      queryTooltipArrow: {
        position: "absolute",
        top: "-6px",
        left: "50%",
        transform: "translateX(-50%)",
        width: "0",
        height: "0",
        borderLeft: "6px solid transparent",
        borderRight: "6px solid transparent",
        borderBottom: `6px solid ${theme.bgPrimary}`,
      },
      queryInputWrapper: { display: "flex", gap: "8px", alignItems: "stretch" },
      queryInput: {
        flex: 1,
        padding: "12px 16px",
        border: `1px solid ${
          isDarkMode ? "rgba(148, 163, 184, 0.2)" : theme.borderSecondary
        }`,
        borderRadius: "10px",
        fontSize: "14px",
        color: theme.textSecondary,
        backgroundColor: isDarkMode ? "rgba(51, 65, 85, 0.5)" : theme.bgPrimary,
        outline: "none",
        fontFamily: "'Inter', 'Segoe UI', sans-serif",
        boxShadow: isDarkMode
          ? "inset 0 1px 3px rgba(0, 0, 0, 0.3)"
          : "inset 0 1px 2px rgba(0, 0, 0, 0.05)",
      },
      queryButton: {
        padding: "10px 24px",
        backgroundColor: theme.accentPrimary,
        color: "white",
        fontSize: "14px",
        fontWeight: "600",
        whiteSpace: "nowrap",
        border: "none",
        borderRadius: "6px",
        cursor: "pointer",
      },
      queryButtonDisabled: {
        backgroundColor: theme.borderSecondary,
        color: theme.textQuaternary,
        cursor: "not-allowed",
      },
      luckyButton: {
        padding: "10px 20px",
        backgroundColor: theme.bgPrimary,
        color: theme.accentPrimary,
        fontSize: "14px",
        fontWeight: "600",
        whiteSpace: "nowrap",
        border: `2px solid ${theme.accentPrimary}`,
        borderRadius: "6px",
        cursor: "pointer",
      },
      queryHint: {
        fontSize: "11px",
        color: theme.textTertiary,
        fontStyle: "italic",
        marginTop: "4px",
      },
      modernResetButton: {
        width: "100%",
        padding: "8px 12px",
        backgroundColor: theme.danger,
        color: "white",
        fontSize: "14px",
        fontWeight: "600",
        border: "none",
        borderRadius: "6px",
        cursor: "pointer",
      },
      insightsTabsContainer: {
        display: "flex",
        gap: "6px",
        backgroundColor: "transparent",
        padding: "0",
        borderRadius: "0",
        border: "none",
      },
      insightsTab: {
        flex: 1,
        padding: "10px 16px",
        borderRadius: "4px",
        fontWeight: "600",
        backgroundColor: "transparent",
        color: theme.textTertiary,
        display: "flex",
        alignItems: "center",
        gap: "6px",
        border: "none",
        fontSize: "12px",
        cursor: "pointer",
        transition: "background-color 0.15s ease, color 0.15s ease",
      },
      insightsTabActive: {
        backgroundColor: theme.accentPrimary,
        color: "white",
      },
      clickForInsightsButton: {
        flex: 1,
        padding: "14px 20px",
        borderRadius: "8px",
        fontWeight: "700",
        backgroundColor: theme.accentPrimary,
        color: "white",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: "8px",
        border: "none",
        fontSize: "14px",
        cursor: "pointer",
        boxShadow: "none",
        transition: "all 0.2s ease",
      },
      tabCount: {
        fontSize: "10px",
        color: "inherit",
        backgroundColor: "rgba(255,255,255,0.2)",
        padding: "2px 6px",
        borderRadius: "8px",
      },
      insightsContext: {
        fontSize: "13px",
        color: theme.accentPrimary,
        fontWeight: "600",
        marginBottom: "4px",
      },
      insightsSubtitle: {
        fontSize: "12px",
        color: theme.textTertiary,
        fontWeight: "400",
        marginBottom: "20px",
      },
      categorySection: { marginBottom: "16px" },
      categoryTitle: {
        fontSize: "14px",
        fontWeight: "600",
        color: theme.textSecondary,
        marginBottom: "12px",
        paddingBottom: "6px",
        borderBottom: `1px solid ${
          isDarkMode ? "rgba(75, 85, 99, 0.2)" : "rgba(229, 231, 235, 0.5)"
        }`,
        display: "flex",
        alignItems: "center",
        gap: "6px",
      },
      insightsList: { display: "flex", flexDirection: "column", gap: "8px" },
      insightItem: {
        padding: "12px 14px",
        backgroundColor: isDarkMode
          ? "rgba(148, 163, 184, 0.08)"
          : theme.bgSecondary,
        borderRadius: "8px",
        border: "none",
        cursor: "pointer",
        display: "flex",
        alignItems: "flex-start",
        gap: "10px",
        transition: "all 0.15s ease",
      },
      insightNumber: {
        fontSize: "12px",
        fontWeight: "700",
        color: theme.accentPrimary,
        minWidth: "16px",
      },
      insightText: {
        fontSize: "13px",
        color: theme.textSecondary,
        lineHeight: "1.55",
        flex: 1,
      },
      summaryTitle: {
        fontSize: "16px",
        fontWeight: "600",
        color: theme.textSecondary,
        marginBottom: showDataSummary ? "16px" : "0px",
        cursor: "pointer",
        display: "flex",
        alignItems: "center",
        gap: "8px",
        userSelect: "none",
      },
      summaryGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
        gap: "12px",
      },
      summaryItem: { fontSize: "13px", color: theme.textTertiary },
      flexBetween: {
        display: "flex",
        alignItems: "center",
        gap: "8px",
        justifyContent: "space-between",
      },
      flexWrap: {
        display: "flex",
        alignItems: "center",
        gap: "8px",
        flexWrap: "wrap",
        flex: "1 1 auto",
      },
      flexGap8: { display: "flex", alignItems: "center", gap: "8px" },
      block: { display: "block" },
      fontWeight600: {
        fontWeight: "600",
        marginBottom: "4px",
        color: theme.textPrimary,
      },
      textGray: { color: theme.textTertiary },
      marginTop12: { marginTop: "12px" },
      guideOverlay: {
        position: "fixed",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: theme.overlayBg,
        zIndex: 2000,
        pointerEvents: "auto",
      },
      guideHighlight: {
        position: "fixed",
        border: `3px solid ${theme.accentPrimary}`,
        borderRadius: "8px",
        boxShadow: `0 0 0 9999px ${theme.overlayBg}`,
        pointerEvents: "none",
        zIndex: 2001,
        boxSizing: "border-box",
      },
      guideTooltip: {
        position: "fixed",
        backgroundColor: theme.bgPrimary,
        borderRadius: "12px",
        zIndex: 2002,
        maxWidth: "400px",
        padding: "16px",
        fontFamily: "'Inter', 'Segoe UI', sans-serif",
        pointerEvents: "auto",
      },
      guideTooltipHeader: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "flex-start",
        marginBottom: "8px",
      },
      guideTooltipTitle: {
        fontSize: "16px",
        fontWeight: "600",
        color: theme.textPrimary,
        marginBottom: "4px",
      },
      guideTooltipStep: {
        fontSize: "12px",
        color: theme.textTertiary,
        fontWeight: "500",
      },
      guideTooltipDescription: {
        fontSize: "14px",
        color: theme.textSecondary,
        lineHeight: "1.5",
        marginBottom: "12px",
      },
      guideTooltipButtons: {
        display: "flex",
        gap: "8px",
        justifyContent: "flex-end",
      },
      guideTooltipButton: {
        padding: "6px 12px",
        borderRadius: "6px",
        border: "none",
        fontSize: "13px",
        fontWeight: "500",
        cursor: "pointer",
      },
      guideTooltipButtonPrimary: {
        backgroundColor: theme.accentPrimary,
        color: "white",
      },
      guideTooltipButtonSecondary: {
        backgroundColor: theme.bgQuaternary,
        color: theme.textSecondary,
      },
      guideTooltipClose: {
        background: "none",
        border: "none",
        fontSize: "20px",
        color: theme.textTertiary,
        cursor: "pointer",
        padding: "0",
        width: "24px",
        height: "24px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: "4px",
      },
      helpButton: {
        position: "absolute",
        top: "-12px",
        right: "12px",
        padding: "6px 12px",
        borderRadius: "16px",
        backgroundColor: theme.accentPrimary,
        color: "white",
        border: "none",
        fontSize: "12px",
        fontWeight: "600",
        cursor: "pointer",
        zIndex: 1500,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        whiteSpace: "nowrap",
        boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
      },
      // Optimization 6: Hoisted styles for .map() loops
      checkboxItemSelected: {
        display: "flex",
        alignItems: "center",
        padding: "6px 8px",
        cursor: "pointer",
        borderRadius: "4px",
        fontWeight: "600",
        backgroundColor: "#f0f9ff",
        borderLeft: `2px solid ${theme.accentPrimary}`,
        paddingLeft: "6px",
        transition: "background-color 0.15s ease, border-left-color 0.15s ease",
      },
      checkboxItemUnselected: {
        display: "flex",
        alignItems: "center",
        padding: "6px 8px",
        cursor: "pointer",
        borderRadius: "4px",
        backgroundColor: "transparent",
        borderLeft: "2px solid transparent",
        paddingLeft: "6px",
        transition: "background-color 0.15s ease, border-left-color 0.15s ease",
      },
      filterSuggestionItemSelected: {
        display: "flex",
        alignItems: "center",
        padding: "8px 12px",
        cursor: "pointer",
        borderBottom: `1px solid ${theme.bgQuaternary}`,
        backgroundColor: isDarkMode ? "rgba(129, 140, 248, 0.15)" : "#f0f9ff",
      },
      filterSuggestionItemUnselected: {
        display: "flex",
        alignItems: "center",
        padding: "8px 12px",
        cursor: "pointer",
        borderBottom: `1px solid ${theme.bgQuaternary}`,
        backgroundColor: isDarkMode ? "rgba(51, 65, 85, 0.3)" : "white",
      },
      categorySelectionItemSelected: {
        display: "flex",
        alignItems: "center",
        padding: "6px 8px",
        borderRadius: "4px",
        cursor: "pointer",
        color: theme.textSecondary,
        backgroundColor: "#f0f9ff",
      },
      categorySelectionItemUnselected: {
        display: "flex",
        alignItems: "center",
        padding: "6px 8px",
        borderRadius: "4px",
        cursor: "pointer",
        color: theme.textSecondary,
        backgroundColor: "transparent",
      },
      categoryLabelText: { fontSize: "13px", color: "#374151" },
      noCategoriesFound: {
        padding: "12px",
        textAlign: "center",
        color: "#6b7280",
        fontSize: "13px",
      },
      radioLabel: {
        display: "flex",
        alignItems: "center",
        cursor: "pointer",
        fontSize: "13px",
      },
      marginRight6: { marginRight: "6px" },
      marginBottom16: { marginBottom: "16px" },
      flexGap12Mt8: { display: "flex", gap: "12px", marginTop: "8px" },
  };
}
